### ISSUE TITLE
Support for Dart 2.12 null safety

### ISSUE THREAD

**Issue by Roshanalexander** [jaweii/Flutter_beautiful_popup#9]
Any plans to support the latest Dart Null Safety? I'm getting the following dependency error when trying to use this package.

`Because image >=2.0.4 <2.1.14 depends on archive >=1.0.16 <3.0.0 and archive ^1.0.2 requires SDK version <2.0.0, image >=2.0.4 <2.1.14 requires archive ^2.0.0.
And because image >=2.1.14 <3.0.0-nullsafety.0 depends on archive ^2.0.0 and every version of flutter_beautiful_popup depends on image ^2.1.4, every version of flutter_beautiful_popup requires archive ^2.0.0.
And because archive >=2.0.0 <3.0.0-nullsafety.0 depends on crypto ^2.0.0 and uuid >=3.0.0 depends on crypto ^3.0.0, flutter_beautiful_popup is incompatible with uuid >=3.0.0.`

**Comment by jaweii** [comment]
Sorry, I have no time to update the package. Seems like it is not a big problem, &nbsp;you can &nbsp;try remove the recolor feature from the source code to solve the problem.

------------------ Original ------------------
From: Roshan Alexander ***@***.***&gt;
Date: Tue,Mar 23,2021 11:16 AM
To: jaweii/Flutter_beautiful_popup ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [jaweii/Flutter_beautiful_popup] Support for Dart 2.12 null safety (#9)





 
Any plans to support the latest Dart Null Safety? I'm getting the following dependency error when trying to use this package.
 
Because image &gt;=2.0.4 <2.1.14 depends on archive &gt;=1.0.16 <3.0.0 and archive ^1.0.2 requires SDK version <2.0.0, image &gt;=2.0.4 <2.1.14 requires archive ^2.0.0. And because image &gt;=2.1.14 <3.0.0-nullsafety.0 depends on archive ^2.0.0 and every version of flutter_beautiful_popup depends on image ^2.1.4, every version of flutter_beautiful_popup requires archive ^2.0.0. And because archive &gt;=2.0.0 <3.0.0-nullsafety.0 depends on crypto ^2.0.0 and uuid &gt;=3.0.0 depends on crypto ^3.0.0, flutter_beautiful_popup is incompatible with uuid &gt;=3.0.0.

**Comment by zikwall** [comment]
This problem is solved by simply updating the dependency, at least I managed to solve it with this method

`image: ^3.0.2`

**Comment by JavonneM** [comment]
I have upgrade the package to use sound null safety with working examples PR #10

**Comment by jaweii** [comment]
> I have upgraded the package to use sound null safety with working examples PR #10

I have published an new version 1.6.0, thank you for your contribution!
